name: CI

on:
  push:
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install Composer dependencies
      uses: "ramsey/composer-install@v3"

    - name: Run PHP-CS-Fixer
      run: composer lint

    - name: Run PHPUnit
      run: composer test

    - name: Run PHPStan
      run: composer phpstan